import React from 'react';
import {ArrowUpRight,Plus,Trash2,MapPin,BriefcaseBusiness,GraduationCap,Award} from 'lucide-react';
const safeUrl=u=>/^https?:\/\//i.test(u)?u:null;
export function ProfileLinks({data}){
 return <div className="profile-links">{data.location&&<span><MapPin size={13}/>{data.location}</span>}{[['github','GitHub'],['linkedin','LinkedIn']].map(([key,label])=>safeUrl(data[key])&&<a key={key} href={safeUrl(data[key])} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={13}/></a>)}</div>;
}
export function ResumeSections({data}){
 return <section className="resume-section section" id="journey"><div className="section-top"><div><div className="eyebrow">03 / LEARNING BY BUILDING</div><h2>The journey so far<span>.</span></h2></div><p>Across intelligent systems, enterprise tools,<br/>and a more secure web.</p></div><div className="resume-layout"><div className="experience-column"><h3 className="resume-label"><BriefcaseBusiness size={15}/> EXPERIENCE</h3><div className="timeline">{(data.experience||[]).map((e,i)=><article className="timeline-entry" key={i}><div className="timeline-dot"/><div className="entry-meta"><span>{e.period}</span><span>{e.location}</span></div><h3>{e.title}</h3><h4>{e.organization}</h4><p>{e.details}</p></article>)}</div></div><div className="learning-column"><h3 className="resume-label"><GraduationCap size={16}/> EDUCATION</h3>{(data.education||[]).map((e,i)=><article className="education-card" key={i}><span className="entry-meta">{e.period}</span><h3>{e.title}</h3><h4>{e.organization}</h4><p>{e.location}</p><strong>{e.details}</strong></article>)}<div className="certifications"><h3 className="resume-label"><Award size={16}/> CERTIFICATIONS</h3><ul>{(data.certifications||[]).map((c,i)=><li key={i}>{c}</li>)}</ul></div><div className="languages"><h3 className="resume-label">LANGUAGES</h3><div className="skill-chips">{(data.languages||[]).map((l,i)=><span key={i}>{l}</span>)}</div></div></div></div></section>;
}
export function ResumeEditor({draft,field}){
 function update(group,index,key,value){field(group,(draft[group]||[]).map((e,i)=>i===index?{...e,[key]:value}:e));}
 return <><p className="muted">Manage your experience, education, certifications, and languages. Entries appear in the order shown below.</p>{['experience','education'].map(group=><section className="resume-editor-group" key={group}><h2>{group==='experience'?'Experience':'Education'}</h2>{(draft[group]||[]).map((e,i)=><div className="editor-card" key={i}><div className="editor-title"><h3>{group==='experience'?'Experience':'Education'} {i+1}</h3><div className="entry-actions"><button disabled={i===0} onClick={()=>{const items=[...draft[group]];[items[i-1],items[i]]=[items[i],items[i-1]];field(group,items);}}>Move up</button><button className="icon-btn" aria-label={`Delete ${group} entry ${i+1}`} onClick={()=>{if(confirm('Remove this entry? Publish changes to confirm.'))field(group,draft[group].filter((_,j)=>i!==j));}}><Trash2 size={16}/></button></div></div><div className="editor-grid">{[['title',group==='experience'?'Role':'Qualification'],['organization',group==='experience'?'Organization':'Institution'],['period','Dates'],['location','Location']].map(([key,label])=><label key={key}>{label}<input value={e[key]} onChange={ev=>update(group,i,key,ev.target.value)}/></label>)}</div><label>{group==='experience'?'Responsibilities & achievements':'Academic details'}<textarea rows={4} value={e.details} onChange={ev=>update(group,i,'details',ev.target.value)}/></label></div>)}<button className="secondary" onClick={()=>field(group,[...(draft[group]||[]),{title:'',organization:'',period:'',location:'',details:''}])}><Plus size={16}/> Add {group==='experience'?'experience':'education'}</button></section>)}{[['certifications','Certifications'],['languages','Languages']].map(([key,title])=><div className="editor-card" key={key}><h3>{title}</h3><label>One entry per line<textarea rows={key==='certifications'?7:4} value={(draft[key]||[]).join('\n')} onChange={e=>field(key,e.target.value.split('\n'))}/></label></div>)}</>;
}
